# 予想
5

毎回のループで`x=i`を実行し、tryが例外を吐き、catchでbreakする前に、finallyのcontinueでiがインクリメントされてからループの最初に戻る。

これを`i<=5`まで続けて、ループをぬけるため、ループ終了時点でxは5となっている。
# 実際の実行結果
5